GET http://localhost:8000/users

###
GET http://localhost:8000/users/1

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "cast",
    "email": "cast@phincon.com",
    "password": "12341234",
    "roleId": "2"
}

###
PATCH http://localhost:8000/users/2
Content-Type: application/json

{
    "name": "Phincon",
    "email": "mphincon@phincon.com",
    "role": "Project Manager"
}

###
DELETE http://localhost:8000/servicesapi/5


###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "syauqi@gmail.com",
    "password": "12345"
}

###
POST http://localhost:8000/services
Content-Type: application/json

{
    "name": "name5",
    "gitlabUrl": "gitlabUrl5",
    "description": "description5",
    "preprodUrl": "preprodUrl5",
    "preprodUrlStatus": "preprodUrlStatus5",
    "prodUrl": "prodUrl5",
    "prodUrlStatus": "prodUrlStatus5",
    "userId": "1"
}

###
DELETE http://localhost:8000/services/4

###
GET http://localhost:8000/services

###
GET http://localhost:8000/services/2


###
PATCH http://localhost:8000/Services/3
Content-Type: application/json

{
    "name": "name5",
    "gitlabUrl": "gitlabUrl3edit",
    "description": "description3edit",
    "preprodUrl": "preprodUrl3edit",
    "preprodUrlStatus": "preprodUrlStatus3edit",
    "prodUrl": "prodUrl3edit",
    "prodUrlStatus": "prodUrlStatus3edit",
    "userId": "2"
}


// Testing Search SERVICE WEB
###
http://localhost:8000/services?search=name2&page=1&limit=10


// Testing Search SERVICE API
###
http://localhost:8000/servicesapi

// Testing GET API
###
http://localhost:8000/api


// Testing Search Service API via id
###
http://localhost:8000/servicesapi/103


###
DELETE http://localhost:8000/servicesapi/104

###
DELETE http://localhost:8000/api/99

###
GET http://localhost:8000/users?page=2&limit=5


###
POST http://localhost:8000/Sonarqube
Content-Type: application/json

{
    "qualityGateStatus": "testingviaBE",
    "bugs": "testingviaBE",
    "vulnerabilities": "testingviaBE",
    "codesmell": "testingviaBE",
    "coverage": "testingviaBE",
    "duplication": "testingviaBE"
}


###
POST http://localhost:8000/unitTesting
Content-Type: application/json

{
    "coverageStatement": 1,
    "coverageBranch": 2,
    "coverageFunction": 3,
    "coverageLines": 4,
    "testCasePassed": 5,
    "testCaseFailed": 6
}



###
POST http://localhost:8000/servicesapi
Content-Type: application/json

{
    "name": "Testing BE baliki ID",
    "gitlabUrl": "1",
    "description": "1",
    "yamlSpec": "1",
    "serviceApiDetailId": "1",
    "sonarCubeId": 1,
    "unitTestingId": 1
}
