GET http://localhost:8000/users

###
GET http://localhost:8000/users/1

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Syauqi3",
    "email": "syauqi3@phincon.com",
    "password": "11111111",
    "roleId": "3"
}

###
PATCH http://localhost:8000/users/4
Content-Type: application/json

{
    "name": "testing3",
    "email": "testing3@phincon.com",
    "password": "22222222",
    "roleId": "3"
}

###
DELETE http://localhost:8000/users/1


###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "syauqi@gmail.com",
    "password": "12345"
}